const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const UPDATE = 'UPDATE';
const SHOW_ERRORS = 'SHOW_ERRORS';
const REMOVE_ERROR = 'REMOVE_ERROR;'
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const GENERATE_KEY = 'GENERATE_KEY';
const DELETE_KEY = 'DELETE_KEY';
const CHANGE_TOKEN = 'CHANGE_TOKEN';

export {
  LOGIN,
  LOGOUT,
  UPDATE,
  SHOW_ERRORS,
  REMOVE_ERROR,
  CLEAR_ERRORS,
  START_LOADING,
  STOP_LOADING,
  GENERATE_KEY,
  DELETE_KEY,
  CHANGE_TOKEN,
};
